__all__ = (
    "WIKIPEDIA_ROOT",
    "INTERNAL_SEGMENT",
    "INTERNAL_LINK_PREFIX",

    "RANDOM_ARTICLE",
    "PHILOSOPHY_ARTICLE",

    "THROTTLE_TIME",
)

WIKIPEDIA_ROOT = "https://en.wikipedia.org"
INTERNAL_SEGMENT = "wiki"
INTERNAL_LINK_PREFIX = WIKIPEDIA_ROOT + "/" + INTERNAL_SEGMENT + "/"

RANDOM_ARTICLE = "Special:Random"
PHILOSOPHY_ARTICLE = "Philosophy"

REQUESTS_PER_SECOND = 2
THROTTLE_TIME = 1.0 / REQUESTS_PER_SECOND
